/*
* Left Join을 한다고 해서 왼쪽것만 가져오는 것이 아니라 거기서 where 절을 해줘야됨
*/
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME
LIMIT 3;